sudo: required
os: linux
dist: trusty
language: python
python:
  - "3.4"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpq-dev python-dev
install:
  - python setup.py install
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - pip install coverage
  - coverage run setup.py test