"""Added the story data table

Revision ID: 3ebfff8e02a6
Revises: f9138511326d
Create Date: 2020-06-13 13:03:51.381778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ebfff8e02a6'
down_revision = 'f9138511326d'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hackernews_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_data_downloaded_at'), 'stories_data', ['downloaded_at'], unique=False)
    op.create_index(op.f('ix_stories_data_hackernews_id'), 'stories_data', ['hackernews_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_data_hackernews_id'), table_name='stories_data')
    op.drop_index(op.f('ix_stories_data_downloaded_at'), table_name='stories_data')
    op.drop_table('stories_data')
    ### end Alembic commands ###
