"""Added indexes to the score and time columns of the stories table

Revision ID: 6cbf482e0583
Revises: a0649018e180
Create Date: 2018-05-27 20:47:57.381973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbf482e0583'
down_revision = 'a0649018e180'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stories_score'), 'stories', ['score'], unique=False)
    op.create_index(op.f('ix_stories_time'), 'stories', ['time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_time'), table_name='stories')
    op.drop_index(op.f('ix_stories_score'), table_name='stories')
    ### end Alembic commands ###
