"""Added the missing unique indexes in the hackernews_users and urls tables

Revision ID: a0649018e180
Revises: f6144e4c6f76
Create Date: 2017-12-11 20:44:05.043496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0649018e180'
down_revision = 'f6144e4c6f76'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hackernews_users', ['username'])
    op.create_unique_constraint(None, 'urls', ['url'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='unique')
    op.drop_constraint(None, 'hackernews_users', type_='unique')
    ### end Alembic commands ###
