"""Added the jti field to the users table

Revision ID: a442f4daf893
Revises: 3210325c0fda
Create Date: 2016-09-30 23:32:16.222872

"""
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a442f4daf893'
down_revision = '3210325c0fda'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jti', sa.String(length=32), nullable=True))
    op.execute("update users set jti = '{}'".format(uuid4().hex))
    op.alter_column('users', 'jti', nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jti')
    ### end Alembic commands ###
