"""Removed the columns related to jwt tokens

Revision ID: b9fac7beb6b9
Revises: 6276344586b8
Create Date: 2018-06-12 22:32:29.942983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fac7beb6b9'
down_revision = '6276344586b8'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'jti')
    ### end Alembic commands ###


def downgrade():
    # The jti has to be nullable because there will an integrity error if users exist
    op.add_column('users', sa.Column('jti', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

