"""Made the value column in the tokens table unique

Revision ID: f9138511326d
Revises: b9fac7beb6b9
Create Date: 2018-06-14 22:19:45.821600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9138511326d'
down_revision = 'b9fac7beb6b9'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tokens', ['value'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='unique')
    ### end Alembic commands ###
