SECRET_KEY = "secret"
TESTING = False
DEBUG = False

CRAWLER_WAIT_TIME = 1.0
CRAWLER_BACKOFF_TIME = 1.0
CRAWLER_ABORT_AFTER = 3

API_HOST = "127.0.0.1"
API_PORT = 5000

ENVIRONMENT = "production"

PROCESSORS = []

PROPAGATE_EXCEPTIONS = True

RABBITMQ_URL_PROCESSOR_HOST = "localhost"
RABBITMQ_URL_PROCESSOR_EXCHANGE = "urls"
RABBITMQ_URL_PROCESSOR_EXCHANGE_TYPE = "topic"
RABBITMQ_URL_PROCESSOR_EXCHANGE_DURABLE = True
RABBITMQ_URL_PROCESSOR_EXCHANGE_AUTO_DELETE = False
RABBITMQ_URL_PROCESSOR_ROUTING_KEY = "urls.new"
RABBITMQ_URL_PROCESSOR_USERNAME = None
RABBITMQ_URL_PROCESSOR_PASSWORD = None

RABBITMQ_STORY_PROCESSOR_HOST = "localhost"
RABBITMQ_STORY_PROCESSOR_EXCHANGE = "stories"
RABBITMQ_STORY_PROCESSOR_EXCHANGE_TYPE = "topic"
RABBITMQ_STORY_PROCESSOR_EXCHANGE_DURABLE = True
RABBITMQ_STORY_PROCESSOR_EXCHANGE_AUTO_DELETE = False
RABBITMQ_STORY_PROCESSOR_ROUTING_KEY = "stories.new"
RABBITMQ_STORY_PROCESSOR_USERNAME = None
RABBITMQ_STORY_PROCESSOR_PASSWORD = None

STORY_DUMP_BATCH_SIZE = 300
